baseURL = 'https://joelyyoung.github.io/'
languageCode = "en-us"
# Website title
title = "Joel Yang"
# Theme used
theme = "hugo-astatine-theme"
# Public dir
publishDir = "docs"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# to support inline HTML code, refer to https://www.bilibili.com/read/cv4516916
[markup]  
  [markup.goldmark]    
    [markup.goldmark.renderer]     
      unsafe = true

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150

# This links to the page about.md
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -110

# This links to the page about.md
[[menu.main]]
    name = "Demo Page"
    url = "/demopage/"
    weight = -100

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -130

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """Joel Yang's blog."""
    # Author of the site
    authorName = "Joel Yang"
    # math
    math = true

    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/main.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # [params.hostedKaTex]
        hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    

    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"