name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to publish branch
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.134.2  # Use the latest Hugo version
    steps:
      # Checkout the master branch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive  # If your Hugo theme uses submodules

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Build Hugo site
      - name: Build
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify # rm docs and rebuild the page
          touch docs/.nojekyll  # Prevent Jekyll processing on GitHub Pages

      # Deploy to publish branch
      - name: Deploy to Publish Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: publish  # Your custom branch for deployment
          publish_dir: ./docs  # Directory to deploy
          keep_files: false  # Overwrite existing content in publish branch