name: Publish homepage

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
      - uses: actions/checkout@v2
        with: 
          ref: master

      - name: Build
        run: |
          mkdir themes
          git clone https://github.com/hugcis/hugo-astatine-theme themes/hugo-astatine-theme
          rm -rf docs/
          hugo --minify
          touch docs/.nojekyll

      # Set github deploy from master branch docs folder!
      - name: Commit docs to master branch)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update example site
          file_pattern: docs/*
