name: Publish homepage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
      - uses: actions/checkout@v2
        with: 
          ref: master

      - name: Ensure publish branch exists
        run: |
          git fetch origin
          if ! git ls-remote --heads origin publish | grep publish; then
            git checkout -b publish
            git push origin publish
          fi

    
      - name: Merge main -> publish
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: 'Merge master in publish'
          from_branch: master
          target_branch: publish
          github_token: ${{ github.token }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
      - uses: actions/checkout@v2
        with: 
          ref: publish

      - name: Build
        run: |
          mkdir themes
          git clone https://github.com/hugcis/hugo-astatine-theme themes/hugo-astatine-theme
          hugo --minify
          rm -rf docs/
          cp -r public/ docs/

      - name: Publish
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update example site
          file_pattern: docs/*
